'use strict'
angular.module('core', [
    'core.index',
    'core.signup',
    'core.login',
    'core.components',
    'core.services',
    'core.procedureContent',
    'core.list',
    'core.listDetails',
    'core.service',
    'core.brand',
    'core.accountVerification',
    'core.forgotPassword',
    'core.contactUs',
    'core.profile',
    'core.dashboard',
    'core.serviceManager',
    'core.followUp',
    'core.documents',
    'core.shoppingCart',
])
